modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/TehStoneMan/CashCraft/issues"

[[mods]]
modId="cashcraft"
version="${version}"
displayName="CashCraft"
updateJSONURL="http://tehstoneman.github.io/cashcraft.json"
displayURL="http://minecraft.curseforge.com/projects/cash-craft"
logoFile="CashCraftLogo.png"
authors="TehStoneMan"
description='''Add a physical currency to your game'''

[[dependencies.cashcraft]]
    modId="forge"
    mandatory=true
    versionRange="[36.0.4,)"
    ordering="NONE"
    side="BOTH"